version: '3.8'

services:

  catalog-management:
    build:
      context: ./backend/catalog-management
      target: dev
    ports:
      - ${BACKEND_CATALOG_MANAGEMENT_PORT}:${BACKEND_CATALOG_MANAGEMENT_PORT}
    volumes:
      - ./backend/catalog-management:/app:delegated
      - /app/node_modules
    environment:
      - PORT=${BACKEND_CATALOG_MANAGEMENT_PORT}

  customer-support:
    build:
      context: ./backend/customer-support
      target: dev
    ports:
      - ${BACKEND_CUSTOMER_SUPPORT_PORT}:${BACKEND_CUSTOMER_SUPPORT_PORT}
    networks:
      default:
      customer-support:
    volumes:
      - ./backend/customer-support:/app:delegated
      - /app/node_modules
    environment:
      - PORT=${BACKEND_CUSTOMER_SUPPORT_PORT}
      - DB_USERNAME=${BACKEND_CUSTOMER_SUPPORT_DB_USERNAME}
      - DB_PASSWORD=${BACKEND_CUSTOMER_SUPPORT_DB_PASSWORD}
      - DB_DATABASE=${BACKEND_CUSTOMER_SUPPORT_DB_DATABASE}
      - DB_HOST=customer-support-db
      - ORDER_PROCESSING_BASE_URL=http://order-processing:${BACKEND_ORDER_PROCESSING_PORT}
    depends_on:
      - customer-support-db
    command: ./wait-for customer-support-db:5432 -- npm run db-migrate-seed

  customer-support-db:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=${BACKEND_CUSTOMER_SUPPORT_DB_USERNAME}
      - POSTGRES_PASSWORD=${BACKEND_CUSTOMER_SUPPORT_DB_PASSWORD}
      - POSTGRES_DB=${BACKEND_CUSTOMER_SUPPORT_DB_DATABASE}
    networks:
      customer-support:
    volumes:
      - customer-support-db-data:/var/lib/postgresql/data

  order-processing:
    build:
      context: ./backend/order-processing
      target: dev
    networks:
      default:
      order-processing:
    volumes:
      - ./backend/order-processing:/app:delegated
      - /app/node_modules
    environment:
      - PORT=${BACKEND_ORDER_PROCESSING_PORT}
      - DB_USERNAME=${BACKEND_ORDER_PROCESSING_DB_USERNAME}
      - DB_PASSWORD=${BACKEND_ORDER_PROCESSING_DB_PASSWORD}
      - DB_DATABASE=${BACKEND_ORDER_PROCESSING_DB_DATABASE}
      - DB_HOST=order-processing-db
    depends_on:
      - order-processing-db
    command: ./wait-for order-processing-db:5432 -- npm run db-migrate-seed

  order-processing-db:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=${BACKEND_ORDER_PROCESSING_DB_USERNAME}
      - POSTGRES_PASSWORD=${BACKEND_ORDER_PROCESSING_DB_PASSWORD}
      - POSTGRES_DB=${BACKEND_ORDER_PROCESSING_DB_DATABASE}
    networks:
      order-processing:
    volumes:
      - order-processing-db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    ports:
      - ${FRONTEND_PORT}:3000
    environment:
      - REACT_APP_CATALOG_MANAGEMENT_BASE_URL=http://localhost:${BACKEND_CATALOG_MANAGEMENT_PORT}
      - REACT_APP_CUSTOMER_SUPPORT_BASE_URL=http://localhost:${BACKEND_CUSTOMER_SUPPORT_PORT}
    stdin_open: true
    depends_on:
      - catalog-management
      - customer-support

networks:
  customer-support:
    driver: bridge
  order-processing:
    driver: bridge

volumes:
  customer-support-db-data:
  order-processing-db-data:
